### ISSUE TITLE
TypeError: Input 'filter' of 'Conv2D' Op has type string that does not match type float32 of argument 'input'.

### ISSUE THREAD

**Issue by dgutyanghs** [cysmith/neural-style-tf#15]
I met a problem in running stylize_image.sh
```
alex@alex-ubuntu1604:~/myprivate/github/neural-style-tf$ bash stylize_image.sh ./image_input/lion.jpg ./styles/kandinsky.jpg

Did you install the required dependencies? [y/n] 
 > y

Do you have a CUDA enabled GPU? [y/n] 
 > y
Rendering stylized image. This may take a while...
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally

---- RENDERING SINGLE IMAGE ----

I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.797
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.40GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)

BUILDING VGG-19 NETWORK
loading model weights...
constructing layers...
LAYER GROUP 1
Traceback (most recent call last):
  File "neural_style.py", line 876, in <module>
    main()
  File "neural_style.py", line 873, in main
    else: render_single_image()
  File "neural_style.py", line 842, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 570, in stylize
    net = build_vgg19(content_img)
  File "neural_style.py", line 248, in build_vgg19
    net['conv1_1'] = conv_layer('conv1_1', net['input'], W=get_weights(vgg_layers, 0))
  File "neural_style.py", line 313, in conv_layer
    conv = tf.nn.conv2d(layer_input, W, strides=[1, 1, 1, 1], padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 521, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type string that does not match type float32 of argument 'input'.
alex@alex-ubuntu1604:~/myprivate/github/neural-style-tf$ 

```

**Comment by dgutyanghs** [comment]
My VGG file(imagenet-vgg-verydeep-19.mat) is error.
after redownload, it works!

**Comment by beraybentesen** [comment]
@dgutyanghs I met with a same problem. Did you change name to solve problem ? I did not understand why redownloading would solve problem.

**Comment by dgutyanghs** [comment]
@beraybentesen As a beginner, I think the file( imagenet-vgg-verydeep-19.mat) have many version,  After downloaded, check the MD5 value of the file, to ensure yours got a correct one!

**Comment by pallaviroyal** [comment]
@dgutyanghs  can you mention the link, from where you downloaded

**Comment by zhangkun0625** [comment]
OK 这个确实是imagenet-vgg-verydeep-19.mat版本问题,换了一个就好了,当前代码对应的文件MD5 106118b7cf60435e6d8e04f6a6dc3657 地址:http://www.vlfeat.org/matconvnet/pretrained/#downloading-the-pre-trained-models
