### ISSUE TITLE
GPU Issue

### ISSUE THREAD

**Issue by jcpsimmons** [cysmith/neural-style-tf#30]
I have the script up and running with the CPU, but it crashes when I try to run it in GPU mode. CUDA and cuDNN are installed. Below is the error:

`Traceback (most recent call last):
  File "neural_style.py", line 872, in <module>
    main()
  File "neural_style.py", line 869, in main
    else: render_single_image()
  File "neural_style.py", line 838, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 572, in stylize
    L_style = sum_style_losses(sess, net, style_imgs)
  File "neural_style.py", line 410, in sum_style_losses
    sess.run(net['input'].assign(img))
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'Variable': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU 
VariableV2: CPU 
	 [[Node: Variable = VariableV2[container="", dtype=DT_FLOAT, shape=[1,512,512,3], shared_name="", _device="/device:GPU:0"]()]]

Caused by op u'Variable', defined at:
  File "neural_style.py", line 872, in <module>
    main()
  File "neural_style.py", line 869, in main
    else: render_single_image()
  File "neural_style.py", line 838, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 566, in stylize
    net = build_model(content_img)
  File "neural_style.py", line 243, in build_model
    net['input']   = tf.Variable(np.zeros((1, h, w, d), dtype=np.float32))
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 293, in _init_from_args
    name=name)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 128, in variable_op_v2
    shared_name=shared_name)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 708, in _variable_v2
    name=name)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/simsies/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'Variable': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU 
VariableV2: CPU 
	 [[Node: Variable = VariableV2[container="", dtype=DT_FLOAT, shape=[1,512,512,3], shared_name="", _device="/device:GPU:0"]()]]

`

**Comment by unhandyandy** [comment]
I'm getting this error too, although the gou works with other programs and Mathematica.

**Comment by benjstern** [comment]
Same here, any feedback would be greatly appreciated.

**Comment by cysmith** [comment]
I followed the installation instructions [here](https://www.tensorflow.org/install/install_linux) for Linux virtualenv. What OS and versions of cuDNN, CUDA, and TensorFlow are you using?

**Comment by benjaminabel** [comment]
I had this problem too: 

     Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; ...

In my case the problem was due to the fact that I had two gpu, the one on the Intel processor and the nvidia one. To fix this I disabled the Intel gpu on the bios. 

Référence: [archlinux wiki](https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Disabling_switchable_graphics)

**Comment by natarslan** [comment]
Same error on Mac. Any advices?

**Comment by lele-lulu** [comment]
I have the same problem. I am using Ubuntu 16.04, cuda 9.0, cudnn 7.0 , tensorflow 1.0.1 and my nvidia is GeForce GTX 1070 Ti
Please help

**Comment by glennamarshall** [comment]
i bypassed ubuntu / bash thing and ran my own direct python call and got the gpu working fine.

**Comment by ivan-rivera** [comment]
I also had that problem but running `pip install tensorflow-gpu` solved it. Give that a try.
