### ISSUE TITLE
NotImplementedError: Negative stop indices are not currently supported

### ISSUE THREAD

**Issue by stanlee321** [cysmith/neural-style-tf#31]
Hi, first of all you,have a great job with all this implementation. I started to test this network but I came with the next problem:
`Did you install the required dependencies? [y/n] 
 > y

Do you have a CUDA enabled GPU? [y/n] 
 > n
Rendering stylized image. This may take a while...

---- RENDERING SINGLE IMAGE ----

BUILDING VGG-19 NETWORK
loading model weights...
constructing layers...
LAYER GROUP 1
--conv1_1 | shape=(1, 512, 512, 64) | weights_shape=(3, 3, 3, 64)
--relu1_1 | shape=(1, 512, 512, 64) | bias_shape=(64,)
--conv1_2 | shape=(1, 512, 512, 64) | weights_shape=(3, 3, 64, 64)
--relu1_2 | shape=(1, 512, 512, 64) | bias_shape=(64,)
--pool1   | shape=(1, 256, 256, 64)
LAYER GROUP 2
--conv2_1 | shape=(1, 256, 256, 128) | weights_shape=(3, 3, 64, 128)
--relu2_1 | shape=(1, 256, 256, 128) | bias_shape=(128,)
--conv2_2 | shape=(1, 256, 256, 128) | weights_shape=(3, 3, 128, 128)
--relu2_2 | shape=(1, 256, 256, 128) | bias_shape=(128,)
--pool2   | shape=(1, 128, 128, 128)
LAYER GROUP 3
--conv3_1 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 128, 256)
--relu3_1 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_2 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_2 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_3 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_3 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_4 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_4 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--pool3   | shape=(1, 64, 64, 256)
LAYER GROUP 4
--conv4_1 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 256, 512)
--relu4_1 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_2 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_2 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_3 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_3 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_4 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_4 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--pool4   | shape=(1, 32, 32, 512)
LAYER GROUP 5
--conv5_1 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_1 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_2 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_2 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_3 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_3 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_4 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_4 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--pool5   | shape=(1, 16, 16, 512)
Traceback (most recent call last):
  File "neural_style.py", line 872, in <module>
    main()
  File "neural_style.py", line 869, in main
    else: render_single_image()
  File "neural_style.py", line 840, in render_single_image
    print('Single image elapsed time: {}'.format(tock - tick))
  File "/home/stanlee321/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3523, in get_controller
    yield default
  File "neural_style.py", line 838, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 612, in stylize
    write_image_output(output_img, content_img, style_imgs, init_img)
  File "/home/stanlee321/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2997, in device
    yield
  File "neural_style.py", line 612, in stylize
    write_image_output(output_img, content_img, style_imgs, init_img)
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 909, in __exit__
    context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/home/stanlee321/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3523, in get_controller
    yield default
  File "neural_style.py", line 578, in stylize
    L_tv = sum_total_variation_losses(sess, net, init_img)
  File "neural_style.py", line 478, in sum_total_variation_losses
    loss_y = tf.nn.l2_loss(x[:,1:,:,:] - x[:,:-1,:,:]) 
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 615, in <lambda>
    setattr(Variable, operator, lambda a, b: Variable._RunOp(operator, a, b))
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 639, in _RunOp
    return getattr(ops.Tensor, operator)(a._AsTensor(), b)
  File "/home/stanlee321/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 315, in _SliceHelper
    "Negative stop indices are not currently supported")
NotImplementedError: Negative stop indices are not currently supported

`

I google a little and It seems an old problem but I don't know the reason by this issue, my Tensorflow version is the 0.10.0rc0, thanks for the feedback.

**Comment by cysmith** [comment]
Hi stanlee,

It looks it is not accepting the [:-1](http://stackoverflow.com/questions/14419206/what-does-1-mean-in-python) in the total variation loss. You can "turn off" the tv loss by setting the weight to 0.

Cam
