### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by simonefil** [cysmith/neural-style-tf#58]
After starting neural_style.py I get this error message:

BUILDING VGG-19 NETWORK
loading model weights...
Traceback (most recent call last):
  File "neural_style.py", line 856, in <module>
    main()
  File "neural_style.py", line 853, in main
    else: render_single_image()
  File "neural_style.py", line 822, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 550, in stylize
    net = build_model(content_img)
  File "neural_style.py", line 240, in build_model
    vgg_rawnet     = scipy.io.loadmat(args.model_weights)
  File "/home/simone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/simone/.pyenv/versions/3.6.5/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

Ca you help me to find a solution?

**Comment by chamoulox** [comment]
It seems like VGG19 (weights) is not in the correct folder or with correct name.

**Comment by wengjun01** [comment]
l have same trouble，are you haved  solution？how to  solved？？

**Comment by simonefil** [comment]
VGG19 is in the correct folder with a correct name. No solution found for the moment

**Comment by wengjun01** [comment]
I haved sloved，l run in windows is ok
